# Generated by Django 2.2.5 on 2020-02-10 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField()),
                ('description', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
